### ISSUE TITLE
Uncaught exception error

### ISSUE THREAD

**Issue by nmhung1985** [portapps/caprine-portable#1]
### Behaviour
The app can't open and shows some Javascript uncaught exception error
#### Steps to reproduce this issue

1. Install the latest version 2.36.0-13
2. Run the app

#### Expected behaviour

> Caprine portable should open

#### Actual behaviour

> The app can't open and shows some Javascript uncaught exception error

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 2.36.0-13

**Operating system (ex. Windows 10 Pro 64 bits)** :  Windows 10 Pro 64 bits

**Winver screenshot** : 
> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

<img width="344" alt="winver" src="https://user-images.githubusercontent.com/39881978/63235280-fbe23400-c262-11e9-83a8-cee1f9ee3c7c.png">

### Screenshots

> If applicable, add screenshots to help explain your problem.
<img width="418" alt="caprine" src="https://user-images.githubusercontent.com/39881978/63235305-13212180-c263-11e9-85ec-b19a3754cc6f.png">

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[caprine-portable.log](https://github.com/portapps/caprine-portable/files/3513958/caprine-portable.log)

**Comment by crazy-max** [comment]
Hi @nmhung1985, thanks for your report. I will fix this issue asap.

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://portapps.io/app/caprine-portable/#download
