### ISSUE TITLE
Block Seen & Typing Indicator

### ISSUE THREAD

**Issue by hansmarcos08** [portapps/caprine-portable#33]
I just downloaded the portable app of this and tested out the block seen and typing indicator it seems that both oh them doesnt work i dont know about the block delivery recepient if its working

**Comment by crazy-max** [comment]
Portapps don't bring support directly to provided apps. If you've got an issue with Caprine, open an issue on the [official repository](https://github.com/sindresorhus/caprine/). Thanks.
