### ISSUE TITLE
2.56.x Error Build

### ISSUE THREAD

**Issue by prpjzz** [portapps/caprine-portable#47]
It seems that Caprine's app.asar is updated or something unknown , so when I tried to build the Portable from your Repo there was a "didn't replace anything" error. Please be able to correct the error and update Caprine to version 2.56.0.

This is my application run: https://github.com/prpjzz/caprine-portable/runs/7940311741

Also, I've updated the app's icon already. You can check it out.

**Comment by crazy-max** [comment]
Should be fixed with latest
