### ISSUE TITLE
Systray icon doesn't update when a new message is received

### ISSUE THREAD

**Issue by Bunnnyface** [portapps/caprine-portable#55]
#### Steps to reproduce this issue

1. Launch caprine-portable.exe
2. Connect with your account.

#### Expected behaviour

> A notification popup in the systray when a new message is received.
#### Actual behaviour

> The systray icon doesn't upadte/change when a new message is received.

### Configuration

**App release / arch** :
2.58.1-38

**Operating system** :
Windows 10 64 bits 22H2

**Comment by crazy-max** [comment]
Maybe #56 would fix it
